version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: chirolife_wordpress
       MYSQL_USER: chirolife-wordpress
       MYSQL_PASSWORD: chirolife-wordpress

   chirolife-wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8080:80"
     volumes:
       - "./chirolife-wordpress:/var/www/html"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: chirolife_wordpress
       WORDPRESS_DB_USER: chirolife-wordpress
       WORDPRESS_DB_PASSWORD: chirolife-wordpress
volumes:
    db_data:
